
language: java
jdk: openjdk8

branches:
  only:
    - /^hotfix.*$/
    - /^feature.*$/
    - develop
    - master

before_cache:
  - find $HOME/.gradle/caches -type f -name '*.lock' -delete
  - find $HOME/.gradle/caches -type f -name 'file-access.bin' -delete
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.gradle/caches/*/scripts*/
  - rm -rf $HOME/.gradle/caches/*/fileHashes/
  - rm -rf $HOME/.gradle/caches/*/workerMain/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/native/
    - $HOME/.gradle/wrapper/

services:
  - mongodb

install:
  # Git set up is required for release tag creation
  - git remote set-url origin https://$GRGIT_USER:$GRGIT_PASS@github.com/hexagonkt/hexagon.git
  - mongo hexagon_benchmark/mongodb.js
  - psql -U postgres -f hexagon_benchmark/postgresql.sql

script: deploy/pre-push

after_failure: echo 'Look for FAILURE in tests'
