
language: java
jdk: openjdk8

branches:
  only:
    - /^hotfix.*$/
    - /^feature.*$/
    - develop
    - master

before_cache:
  - find $HOME/.gradle/caches -type f -name '*.lock' -delete
  - find $HOME/.gradle/caches -type f -name 'file-access.bin' -delete
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.gradle/caches/*/scripts*/
  - rm -rf $HOME/.gradle/caches/*/fileHashes/
  - rm -rf $HOME/.gradle/caches/*/workerMain/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/native/
    - $HOME/.gradle/wrapper/

services:
  - docker

script: ./gradlew clean all

after_failure: echo 'Look for FAILURE in tests'
