#
# Containers and Images
# Check `README.md` for usage instructions.
#

version: '3'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16

services:

  mongodb:
    image: mongo:4.2.0
    networks:
      default:
        ipv4_address: 10.20.0.10

  frontend:
    image: nginx:1.15
    labels:
      app: realworld
      type: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/build/web:/usr/share/nginx/html:ro
    networks:
      default:
        ipv4_address: 10.20.0.20

  backend:
    image: ${registry:-}realworld:0.1
    labels:
      app: realworld
      type: backend
    depends_on:
      - mongodb
    environment:
      SERVICE_mongodbUrl: mongodb://mongodb/real_world
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      default:
        ipv4_address: 10.20.0.30
