#
# Containers and Images
# Check `README.md` for usage instructions.
#

version: '3'

services:

  mongodb:
    image: mongo:4.2.0
    ports:
      - 3010:27017

  frontend:
    image: nginx:1.15
    labels:
      app: realworld
      type: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/build/web:/usr/share/nginx/html:ro
    ports:
      - 3080:80

  backend:
    image: ${registry:-}realworld:1.0
    labels:
      app: realworld
      type: backend
    depends_on:
      - mongodb
    environment:
      SERVICE_mongodbUrl: mongodb://mongodb/real_world
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 3090:9090
