
apiVersion: v1

kind: ReplicationController

metadata:
  name: realworld

spec:
  replicas: 1
  selector:
    app: realworld
  template:
    metadata:
      name: realworld
      labels:
        app: realworld
    spec:
      containers:
        - name: realworld
          image: 487943794540.dkr.ecr.eu-west-1.amazonaws.com/sample:0.1
          ports:
            - containerPort: 9090
