
bindPort : 9090
bindAddress : 0.0.0.0

routesApiEndpoint : https://services-api.ryanair.com/locate/3/routes
schedulesApiEndpoint : https://services-api.ryanair.com/timtbl/3/schedules

maxConnectionMinutes : 120
